# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.4
language: swift
xcode_workspace: Example/SweetLike.xcworkspace
xcode_scheme: SweetLike-Example
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11
podfile: Example/Podfile

before_install:
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SweetLike.xcworkspace -scheme SweetLike-Example -sdk iphonesimulator13.4 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

notifications:
  slack: demirciy:pzu0mBJfP9CAy16arOxASvjF
  email:
    recipients:
      - demirciy94@gmail.com
    on_success: never
    on_failure: always

branches:
  only:
    - development
