# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.4
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
#script:
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SweetLike.xcworkspace -scheme SweetLike-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint

notifications:
  slack: demirciy:pzu0mBJfP9CAy16arOxASvjF
  email:
    recipients:
      - demirciy94@gmail.com
    on_success: never
    on_failure: always

branches:
  only:
    - development
